name: Build Docker images (ngtcp2)
on:
  push:
    branches: [ ngtcp2 ]
  pull_request:
    branches: [ ngtcp2 ]

jobs:
  endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build endpoint
        uses: docker/build-push-action@v2
        with:
          context: endpoint/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/tatsuhiro-t/quic-network-simulator-endpoint:latest
